
const PROXY_HTTPS = '/https/';

export const COMMON_DEV_HOSTS = {
    LOTTERY_URL: PROXY_HTTPS + 'lottery-bt.wildberries.ru/lottery/api/v1/lottery',
    LOTTERY_URL_PURCHASE: PROXY_HTTPS + 'lottery-bt.wildberries.ru/lottery/api/v2/lottery',
    DBS_CODES_API_URL: PROXY_HTTPS + 'dbs-codes.wildberries.ru',
    NNSZ_API_URL_STAGE: PROXY_HTTPS + 'wbx-oof-ingress-controller.wbx-oof.k8s.stage-dm',
    NNSZ_API_URL: 'https://wbxoofex.wildberries.ru',
    SYNC_API_URL: PROXY_HTTPS + 'user-data-syncer.wb.ru',
    STIMULUS_API_URL: PROXY_HTTPS + 'napi.wildberries.ru/api/basket/stimulus',
    LOYALTY_CARDS_API_URL: 'https://user-grade.wildberries.ru/loyalty/api',
    PROMOCODE_URL_API: PROXY_HTTPS + 'promocod-calculator.wildberries.ru/api/v1/promocodes',
    USERGRADE_API_URL: 'http://user-grade-proxy.wbx-user-storage.k8s.stage-xc/api',
    ALL_PICKUPS_NAME: 'all-poo-fr-v9-stage-nnsz.json',
    ALL_PICKUPS_HASH_NAME: 'all-poo-v9-stage-nnsz.json.hash',
    PROXY_HTTPS: PROXY_HTTPS,
    CATALOG_URL: PROXY_HTTPS + 'catalog.wb.ru/',
    SEARCH_URL: PROXY_HTTPS + 'search.wb.ru/',
    RECOM_URL: PROXY_HTTPS + 'recom.wb.ru/',
    CARD_URL: PROXY_HTTPS + 'card.wb.ru/',
    CATALOG_PROXY_URL: '/__internal/catalog/',
    SEARCH_PROXY_URL: '/__internal/search/',
    RECOM_PROXY_URL: '/__internal/recom/',
    CARD_PROXY_URL: '/__internal/card/',
    CATALOG_UNREG_URL: PROXY_HTTPS + 'u-catalog.wb.ru/',
    SEARCH_UNREG_URL: PROXY_HTTPS + 'u-search.wb.ru/',
    RECOM_UNREG_URL: PROXY_HTTPS + 'u-recom.wb.ru/',
    CARD_UNREG_URL: PROXY_HTTPS + 'u-card.wb.ru/',
    CATALOG_UNREG_PROXY_URL: '/__internal/u-catalog/',
    SEARCH_UNREG_PROXY_URL: '/__internal/u-search/',
    RECOM_UNREG_PROXY_URL: '/__internal/u-recom/',
    CARD_UNREG_PROXY_URL: '/__internal/u-card/',
    SEARCH_TAGS_URL: PROXY_HTTPS + 'search-tags.wb.ru/',
    SEARCH_UNREG_TAGS_URL: PROXY_HTTPS + 'u-search-tags.wb.ru/',
    SEARCH_TAGS_PROXY_URL: '/__internal/search-tags/',
    SEARCH_UNREG_TAGS_PROXY_URL: '/__internal/u-search-tags/',
    SUGGESTS_URL: PROXY_HTTPS + 'suggests.wb.ru/',
    SUGGESTS_UNREG_URL: PROXY_HTTPS + 'u-suggests.wb.ru/',
    SUGGESTS_PROXY_URL: '/__internal/suggests/',
    SUGGESTS_UNREG_PROXY_URL: '/__internal/u-suggests/',
    META_URL: PROXY_HTTPS + 'meta.wb.ru/',
    META_PROXY_URL: '/__internal/meta/',
    BANNERS_SEARCH_URL: PROXY_HTTPS + 'banners.wb.ru/',
    BANNERS_SEARCH_PROXY_URL: '/__internal/banners/',
    USER_GEO_DATA_URL: PROXY_HTTPS + 'user-geo-data.wildberries.ru/',
    USER_GEO_DATA_PROXY_URL: '/__internal/user-geo-data/',
    CART_STORAGE_URL: PROXY_HTTPS + 'cart-storage-api.wildberries.ru/api/basket',
    RETURNS_URL: PROXY_HTTPS + 'returns.wildberries.ru/returns/api/v1/claims',
    CART_STORAGE_PROXY_URL: '/__internal/cart-storage-api/api/basket',
    CHAT_SELLERS_BY_RU_URL: PROXY_HTTPS + 'chat.wildberries.ru/api/sellers-chat-1/',
    CHAT_SELLERS_BY_BY_URL: PROXY_HTTPS + 'chat.wildberries.by/api/sellers-chat-1/',
    CHAT_SELLERS_BY_AM_URL: PROXY_HTTPS + 'chat.wildberries.am/api/sellers-chat-1/',
    CHAT_SELLERS_BY_KZ_URL: PROXY_HTTPS + 'chat.wildberries.kz/api/sellers-chat-1/',
    CHAT_SELLERS_BY_KG_URL: PROXY_HTTPS + 'chat.wildberries.kg/api/sellers-chat-1/',
    CHAT_SELLERS_BY_UZ_URL: PROXY_HTTPS + 'chat.wildberries.uz/api/sellers-chat-1/',
    CHAT_SELLERS_BY_TJ_URL: PROXY_HTTPS + 'chat.wildberries.tj/api/sellers-chat-1/',
    CHAT_SELLERS_STAGE_URL: PROXY_HTTPS + 'chat-stage.wildberries.ru/api/sellers-chat-1/',
    CHAT_COURIER_URL: PROXY_HTTPS + 'chat-ingress-controller.chat.k8s.stage-dm/api/courier-chat-srv/',
    FAVS_STORAGE_URL: PROXY_HTTPS + 'favs-storage-api.wildberries.ru/api/favs',
    FAVS_STORAGE_PROXY_URL: '/__internal/favs-storage-api/api/favs',
    INSTALLMENTS_AGGREGATOR_URL: PROXY_HTTPS + 'installments-aggregator-bt.wildberries.ru/installments-aggregator',
    CUSTOMER_SUBSCRIPTIONS_URL: PROXY_HTTPS + 'gateway-subscriptions.common.geo.paywb.com',
    WISH_LIST_URL: PROXY_HTTPS + 'wishlist.dev.paywb.com',
    HIGHLIGHT_URL: PROXY_HTTPS + 'highlight.wildberries.ru', // сервис премиум юзеров (отзывы и вопросы)
    PIN_USER_URL: PROXY_HTTPS + 'pin.wb.ru/pin-user-api/api/v1/pin/w/card/',
    AUTH_URL: PROXY_HTTPS + 'wbx-auth.wildberries.', // нужен домен
    AUTHV3_URL: PROXY_HTTPS + 'wbx-authv3.wildberries.', // нужен домен
    AUTH_INTERNAL_URL: PROXY_HTTPS + 'wbx-auth-internal.wildberries.ru',
    OAUTH_URL: PROXY_HTTPS + 'oauth.wildberries.ru', // oauth-stage.wildberries.ru,
    BASKET_RU_INTERNAL_API_URL: PROXY_HTTPS + 'ru-basket-api.wildberries.ru',
    BASKET_RU_API_URL: PROXY_HTTPS + 'ru-basket-api.wildberries.ru',
    BASKET_API_URL: PROXY_HTTPS + 'basket-api.wildberries.', // нужен домен
    CHAT_RU_URL: PROXY_HTTPS + 'chat-prod.wildberries.ru',
    CHAT_BY_URL: PROXY_HTTPS + 'chat-prod.wildberries.by',
    CHAT_AM_URL: PROXY_HTTPS + 'chat-prod.wildberries.am',
    CHAT_KZ_URL: PROXY_HTTPS + 'chat-prod.wildberries.kz',
    CHAT_KG_URL: PROXY_HTTPS + 'chat-prod.wildberries.kg',
    CHAT_UZ_URL: PROXY_HTTPS + 'chat-prod.wildberries.uz',
    CHAT_TJ_URL: PROXY_HTTPS + 'chat-prod.wildberries.tj',
    CHAT_TRAVEL_BY_RU_URL: PROXY_HTTPS + 'chat-prod.wildberries.ru/api/wbtravel-wb-chat',
    CHAT_REALTY_BY_RU_URL: PROXY_HTTPS + 'chat-prod.wildberries.ru/api/realty-wb-chat',
    CHAT_EAPTEKA_BY_RU_URL: PROXY_HTTPS + 'chat-prod.wildberries.ru/api/eapteka-wb-chat',
    CHAT_RU_STAGE_URL: PROXY_HTTPS + 'chat-stage.wildberries.ru',
    WBX_BELL_URL: PROXY_HTTPS + 'wbx-bell-v3.wildberries.ru',
    SHOPPER_BT_URL: PROXY_HTTPS + 'shopper-bt.wb.ru',
    FIN_PERSON_INSTALLMENT_URL: PROXY_HTTPS + 'fin-person-installment.wildberries.ru',
    CUSTOMS_URL: PROXY_HTTPS + 'customs.wb.ru', // Сервис для отправки перс данных для таможни (customs-beta.wb.ru - стейджевый)
    DELIVERY_CODE_URL: PROXY_HTTPS + 'betta-stg.wildberries.ru/delivery-code/api/v1',
    POINTS_USERS_URL: PROXY_HTTPS + 'points.wb.ru/points-users-api/api/', //Сервис баллов за отзывы
    FEEDBACKS_URL: PROXY_HTTPS + 'feedbacks{0}.wb.ru',
    FEEDBACK_SERVICE_NEW_URL: PROXY_HTTPS + 'feedbacks3-api.wb.ru/api/user/feedback/', // Отправка отзыва в новый сервис отзывов
    QUESTIONS_URL: PROXY_HTTPS + 'question-service-stage.wb.ru/api/v1', // Сервис вопросов
    QUESTIONS_DELETE_URL: 'https://feedback-bt-preprod.wb.ru', // Сервис удаления вопросов
    FEEDBACK_SERVICE_RESALE_NEW_URL: PROXY_HTTPS + 'feedback-c2c-fbapi.wildberries.ru/api/user/feedback/', // Отправка отзыва в новый сервис ресейл
    BASE_REASONS_URL: PROXY_HTTPS + 'reviews-reasons.wb.ru/reviews-reasons', // Сервис причин отзывов
    BPL_URL: PROXY_HTTPS + 'bnpl-gateway.wildberries.ru',
    GIFTCARDS_URL: PROXY_HTTPS + 'giftcards.wildberries.ru',
    ASTRO_URL: PROXY_HTTPS + 'astro.wildberries.ru', // API GateWay Astro
    SELLER_RECOM_URL: 'https://rec-ins.wildberries.ru/api/v1/recommendations',
    SELLER_RECOM_NEW_URL: 'https://static-basket-08.wbbasket.ru/vol154/content-recommendations',
    GENERATIVE_FEEDBACKS_URL: PROXY_HTTPS + 'reviews-sum.wildberries.',
    TRAVEL_PROMO_URL: PROXY_HTTPS + 'travel-stage.wb.ru/stream/api/avia-service/v1',
    TRACKER_RU_URL:PROXY_HTTPS + 'wbx-status-tracker.wildberries.ru/api',
    TRACKER_BY_URL:PROXY_HTTPS + 'wbx-status-tracker.wildberries.by/api',
    TRACKER_AM_URL:PROXY_HTTPS + 'wbx-status-tracker.wildberries.am/api',
    TRACKER_KZ_URL:PROXY_HTTPS + 'wbx-status-tracker.wildberries.kz/api',
    TRACKER_KG_URL:PROXY_HTTPS + 'wbx-status-tracker.wildberries.kg/api',
    TRACKER_UZ_URL:PROXY_HTTPS + 'wbx-status-tracker.wildberries.uz/api',
    TRACKER_TJ_URL:PROXY_HTTPS + 'wbx-status-tracker.wildberries.tj/api',
    KING_PROXY_URL: 'wbx-site-utility-ingress-controller.wbx-site-utility.k8s.stage-el',
    APPS_CONFIG_URL: PROXY_HTTPS + 'apps-config.wildberries.ru/config/api/v2/config?v=1&l=ru&t=wbx-web',
    C2C_URL: 'https://resale-api-stg.wildberries.ru',
    // C2C_URL: PROXY_HTTPS + 'resale-api.wildberries.ru', // Для чатов C2C использовать продовую ручку
    C2C_FEEDBACK_QUESTIONS_URL: PROXY_HTTPS + 'feedback-bt.wildberries.ru',
    FEEDBACK_TRANSLATE_URL: PROXY_HTTPS + 'feedback-bt.wildberries.ru',
    FEEDBACK_BT_LK_URL: PROXY_HTTPS + 'feedback-bt.wildberries.ru',
    WALLET_URL: PROXY_HTTPS + 'wb-wallet.wildberries.ru/wb-wallet',
    WALLET_AUTH_URL: PROXY_HTTPS + 'finance.wildberries.ru',
    WB_GEOCODING_URL: 'https://wb-maps.wb.ru/api/geocoder',
    SEARCH_BY_IMAGE_URL: 'https://search-by-photo.wb.ru',
    PATHFINDER_URL: PROXY_HTTPS + 'betta-preprod.wildberries.ru',
    JOURNAL_HOST: PROXY_HTTPS + 'betta-stg.wildberries.ru/journal', // https://gitlab.wildberries.ru/betta/mobile/back/journal/-/tree/master?ref_type=heads
    WEB_PUSH_URL: PROXY_HTTPS + 'wbx-bell-pushtokens.wildberries.ru',
    BALANCE_HISTORY_URL: PROXY_HTTPS + 'wb-balance.wildberries.ru/wb-balance/api/v2/balance/history',
    BALANCE_URL: PROXY_HTTPS + 'wb-balance.wildberries.ru/wb-balance/api',
    WALET_TRANSACTION_INFO_URL: PROXY_HTTPS + 'wb-wallet.wildberries.ru/wb-wallet/api/v1/wallet/tx/info',
    FEEDBACKS_C2C_URL: 'https://feedback-c2c-view.wildberries.ru',
    QUESTIONS_C2C_URL: 'https://question-c2c.wildberries.ru/api/v1',
    BANNERS_URL: PROXY_HTTPS + 'banners-website.wildberries.ru/public/v2/banners',
    SESSION_URL: PROXY_HTTPS + 'auth-gateway.wildberries.ru',
    SESSION_URL_AUTHV3: PROXY_HTTPS + 'authv3-gateway.wildberries.ge',
    WBX_API_GATEWAY: PROXY_HTTPS + 'wbx-api-gateway.wildberries.ru',
    PDL_PROXY_URL: PROXY_HTTPS + 'installments.wildberries.ru/installments',
    PAYWB_API: PROXY_HTTPS + 'paywb.com',
    DELIVERY_ASSIST_URL: PROXY_HTTPS + 'delivery-assist.wildberries.ru',
    WB_COURIER_TIME_SLOTS_URL: PROXY_HTTPS + 'delivery-assist.wildberries.ru/delivery-assist/api/v1/orders/courier/conditions', // интервалы FBS и WH не КГТ
    SELLERS_SYNCER_URL: PROXY_HTTPS + 'user-data-syncer.wb.ru/sellers-syncer/api/v1/sellers',
    SELLERS_ENRICH_URL: PROXY_HTTPS + 'user-data-syncer.wb.ru/sellers/api/v1/enrich_sellers',
    BRANDS_SYNCER_URL: PROXY_HTTPS + 'user-data-syncer.wb.ru/sellers-syncer/api/v1/brands',
    BRANDS_ENRICH_URL: PROXY_HTTPS + 'user-data-syncer.wb.ru/sellers/api/v1/enrich_brands',
    SMART_CALENDAR_DAYS_URL: PROXY_HTTPS + 'delivery-bt.wildberries.ru/delivery/api/v1/sources/by/locations/wbgo', // доступные дни для умн календаря (WBGO)
    REALTY_URL: 'https://realty.common.geo.paywb.com/',
    DELIVERY_BT: PROXY_HTTPS + 'delivery-bt.wildberries.ru',
    DELIVERY_PRICE: PROXY_HTTPS + 'deliveryprice.wildberries.ru',
    SENTRY_DSN: '',
    INSURANCIES_API: PROXY_HTTPS + 'product-insurance.wildberries.ru/app-gateway',
    TEXT_REPORT: 'http://native-review.wbx-site.k8s.stage-el/api/v1/send-message',
    PHARMA_RECOM_URL: PROXY_HTTPS + 'pharma-recom.wb.ru/',
    ORCHESTRATOR_URL: PROXY_HTTPS + 'orders-collector.wildberries.ru/orders-gateway/api/v1/order/save',
    INVEST_PLATFORM_URL: PROXY_HTTPS + 'invest.wildberries.ru',
};

export default COMMON_DEV_HOSTS;
