MBTN_LEFT       cycle pause
[               add speed -0.01
]               add speed 0.01
{         add speed -0.1
}         add speed 0.1
BS              set speed 1.0
LEFT    seek -5
RIGHT   seek  5
Shift+LEFT    seek -60
Shift+RIGHT   seek  60
F11  cycle fullscreen
